import type { ModelInfo } from '@/types/model';

const getBasePath = (): string => {
  if (import.meta.env.DEV) {
    return '';
  }
  return import.meta.env.BASE_URL || '/';
};

const BASE_PATH = getBasePath();

export const YOLO_MODELS: ModelInfo[] = [
  {
    id: 'yolo11n',
    name: 'YOLOv11n Detection',
    description: 'General object detection (80 classes)',
    file: `${BASE_PATH}models/yolo11n.onnx`,
    type: 'detection',
    inputShape: [1, 3, 640, 640],
    outputFormat: '[1, 84, 8400]', // 4 bbox + 80 classes
  },
  {
    id: 'yolo11n-seg',
    name: 'YOLOv11n Segmentation',
    description: 'Instance segmentation with masks',
    file: `${BASE_PATH}models/yolo11n-seg.onnx`,
    type: 'segmentation',
    inputShape: [1, 3, 640, 640],
    outputFormat: '[1, 116, 8400]', // 4 bbox + 80 classes + 32 mask
  },
];

export const POSE_KEYPOINT_NAMES = [
  'nose',
  'left_eye',
  'right_eye',
  'left_ear',
  'right_ear',
  'left_shoulder',
  'right_shoulder',
  'left_elbow',
  'right_elbow',
  'left_wrist',
  'right_wrist',
  'left_hip',
  'right_hip',
  'left_knee',
  'right_knee',
  'left_ankle',
  'right_ankle',
];

export const COCO_CLASSES = [
  'person',
  'bicycle',
  'car',
  'motorcycle',
  'airplane',
  'bus',
  'train',
  'truck',
  'boat',
  'traffic light',
  'fire hydrant',
  'stop sign',
  'parking meter',
  'bench',
  'bird',
  'cat',
  'dog',
  'horse',
  'sheep',
  'cow',
  'elephant',
  'bear',
  'zebra',
  'giraffe',
  'backpack',
  'umbrella',
  'handbag',
  'tie',
  'suitcase',
  'frisbee',
  'skis',
  'snowboard',
  'sports ball',
  'kite',
  'baseball bat',
  'baseball glove',
  'skateboard',
  'surfboard',
  'tennis racket',
  'bottle',
  'wine glass',
  'cup',
  'fork',
  'knife',
  'spoon',
  'bowl',
  'banana',
  'apple',
  'sandwich',
  'orange',
  'broccoli',
  'carrot',
  'hot dog',
  'pizza',
  'donut',
  'cake',
  'chair',
  'couch',
  'potted plant',
  'bed',
  'dining table',
  'toilet',
  'tv',
  'laptop',
  'mouse',
  'remote',
  'keyboard',
  'cell phone',
  'microwave',
  'oven',
  'toaster',
  'sink',
  'refrigerator',
  'book',
  'clock',
  'vase',
  'scissors',
  'teddy bear',
  'hair drier',
  'toothbrush',
];
